### ISSUE TITLE
If you use it with styled-components, you get a warning

### ISSUE THREAD

**Issue by orot-donghee** [The-Code-Monkey/styled-system#417]
The latest styled-component is supposed to spend $, but it should be updated.

styled-components: it looks like an unknown prop "mb" is being sent through to the DOM, which will likely trigger a React console error. If you would like automatic filtering of unknown props, you can opt-into that behavior via `<StyleSheetManager shouldForwardProp={...}>` (connect an API like `@emotion/is-prop-valid`) or consider using transient props (`$` prefix for automatic filtering.)

**Comment by The-Code-Monkey** [comment]
Hi There, thanks for taking the time to submit the issue,

styled-system is fully compatible with styled-components, the reason there is no filtering is that from the point that styled-system interfaces with styled-components there isn't a way to stop this error.

These are the current 2 solutions:

```
import isPropValid from '@emotion/is-prop-valid';

<StyleSheetManager shouldForwardProp={isPropValid}>
...
</StyleSheetManager>
```

or something like this https://github.com/The-Code-Monkey/TechStack/blob/6508c2c4dc0ff3cc4d4f991cd1eeae0189875b91/packages/components/src/utils/shouldForwardProp.ts#L8 But this is more manual and should be avoided as it would have to be added to every styled component like so

```
export const StyledBoxProps = compose(
  space,
  color,
  layout,
  position,
  border,
  shadow,
  flexbox,
  typography,
  transition,
  utilProps,
  defaultStyles
);

export const StyledBox = styled.div.withConfig({
  shouldForwardProp: shouldForwardProp(StyledBoxProps.propNames),
})`
```

Please let me know if you need any more help. I might add the ability to prefix the props with `$` in the future but its not a personal preference as I believe it makes the code harder to read.

**Comment by orot-donghee** [comment]
export const StyledBoxProps = compose(
  space,
  color,
  layout,
  position,
  border,
  shadow,
  flexbox,
  typography,
  transition,
  utilProps,
  defaultStyles
);

export const StyledBox = styled.div.withConfig({
  shouldForwardProp: shouldForwardProp(StyledBoxProps.propNames),
})`

I'm doing it this way

But can you tell me where to call shoulderForwardProp??

I'm using styled-component, not emotion

**Comment by orot-donghee** [comment]
my code
`import {
  border,
  BorderProps,
  color,
  ColorProps,
  flexbox,
  FlexboxProps,
  layout,
  LayoutProps,
  position,
  PositionProps,
  shadow,
  ShadowProps,
  space,
  SpaceProps,
  typography,
  TypographyProps
} from '@techstack/styled-system';
import styled from 'styled-components';

type BoxProps = SpaceProps &
  LayoutProps &
  ColorProps &
  FlexboxProps &
  BorderProps &
  PositionProps &
  ShadowProps &
  TypographyProps;


const Box = styled.div<BoxProps>`
  ${space}
  ${layout}
  ${color}
  ${flexbox}
  ${border}
  ${position}
  ${shadow}
  ${typography}
`;

export default Box;
`

**Comment by orot-donghee** [comment]
Thanks to you, it's been resolved

Thank you.

**Comment by The-Code-Monkey** [comment]
No worries, yeah the version on the style sheet manager is better but if you are doing it for a component lib, the per styled definition is better.

**Comment by The-Code-Monkey** [comment]
@orot-donghee please let me know when you put your code on GitHub, it would be nice to see some useages
