### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by nazmeln** [The-Code-Monkey/styled-system#466]
Hey,
Could you tell me please if it's working with React Native styled-components lib?

**Comment by The-Code-Monkey** [comment]
Hi im not sure as I don't do react native but if you could try and let me
know

**Comment by nazmeln** [comment]
@The-Code-Monkey I’be tried to add it to the project, but got an error related to the node version. It's mentioned that the required node version should be > 18 and my project uses v16.20.

**Comment by The-Code-Monkey** [comment]
Hi reason for supporting node > 18 is because 16 is now end of life and
shouldn't really be used anymore

**Comment by The-Code-Monkey** [comment]
@nazmeln have you tried upgrading the project to node 18

**Comment by wesleyguirra** [comment]
@The-Code-Monkey React-Native still uses 16 even if it's in the end of life, to support RN it matters to also be in 16

**Comment by The-Code-Monkey** [comment]
@wesleyguirra from what I can see on the react native repo is that the latest version is >18. Check the engines field

https://github.com/facebook/react-native/blob/main/packages/react-native/package.json

**Comment by The-Code-Monkey** [comment]
Please correct me if I am wrong I don't use native, I can check with guys at work tomorrow though

**Comment by The-Code-Monkey** [comment]
Closing due to no response.
