### ISSUE TITLE
mixing array props and inheritance

### ISSUE THREAD

**Issue by Kikobeats** [The-Code-Monkey/styled-system#640]
Giving this base component declaration:

```js
const Text = styled('div')(
  typography
)

Text.defaultProps = {
  fontSize: [1, 1, 2, 2]
}
```

and creating a new one that use it:

```js
const Caps = styled(Text)``
```

If I try to redefine `defaultProps`, it seems the original array declaration is taking precedence:

This doesn't work:

```js
Caps.defaultProps = {
  fontSize: 0 // fontSize is still [1, 1, 2, 2]
}
```

This works:

```js
Caps.defaultProps = {
  fontSize: [0, 0, 0 0]
}
```

I'm using this last as workaround, but ideally to avoid confusion I think defaultProps should always be overriden.

**Comment by The-Code-Monkey** [comment]
I'm not sure on this one as I don't use default props in this way and I also believe this isnt the react recommended way so side effects may exists.

**Comment by The-Code-Monkey** [comment]
This might be a styled components issue I'll have to take a look

**Comment by The-Code-Monkey** [comment]
From testing all i can see is that for some reason.

// doesnt work
const Text = styled('div')(
  typography
)

// does work
const Text = styled.div`
${typography}
`;

**Comment by The-Code-Monkey** [comment]
[Sandbox](https://codesandbox.io/p/sandbox/styled-components-3tmvb?file=%2FTitle.js%3A10%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr0pmesa00063b6ijo1dblwu%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr0pmesa00023b6ioruzdixe%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr0pmesa00033b6imuicbm7c%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr0pmesa00053b6iwkfu8x2f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr0pmesa00023b6ioruzdixe%2522%253A%257B%2522id%2522%253A%2522clr0pmesa00023b6ioruzdixe%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr0pmes900013b6iqlzqgvre%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr0pmes900013b6iqlzqgvre%2522%257D%252C%2522clr0pmesa00053b6iwkfu8x2f%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr0pmesa00043b6i5w1c9b53%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clr0pmesa00053b6iwkfu8x2f%2522%252C%2522activeTabId%2522%253A%2522clr0pmesa00043b6i5w1c9b53%2522%257D%252C%2522clr0pmesa00033b6imuicbm7c%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clr0pmesa00033b6imuicbm7c%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) change <Title> for <Test> and you can see the stuff work

**Comment by Kikobeats** [comment]
After removing my defaultProps, it's back to fine
