### ISSUE TITLE
is `compose` really necessary?

### ISSUE THREAD

**Issue by Kikobeats** [The-Code-Monkey/styled-system#641]
What's the difference between:

```js
import styled from 'styled-components'
import { compose, typography, space, color } from '@techstack/styled-system'
 
export const Text = styled('div')(
  compose(
    typography,
    space,
    color
  )
)
```

and

```js
import styled from 'styled-components'
import { typography, space, color } from '@techstack/styled-system'
 
export const Text = styled('div')(
    typography,
    space,
    color
)
```

The only thing documentation is saying is:

> The compose utility is used to combine multiple style functions together into one. This utility can help improve performance when using multiple style props functions on the same component.

Still it's unclear why it's necessary 🤔

**Comment by The-Code-Monkey** [comment]
When using multiple individual functions e.g. space, typography. The internal logic of styled system has to run once per function when placing them inside compose it runs it once for all the combined functional logic. As the space function is more of a config than an actual function.

**Comment by Kikobeats** [comment]
clarified, thanks!

**Comment by The-Code-Monkey** [comment]
No worries.
