### ISSUE TITLE
padding props parse values smaller than 1 to 0 

### ISSUE THREAD

**Issue by desouky95** [The-Code-Monkey/styled-system#744]
# Spacing Props parse values smaller than 1 to 0

### Padding and margin values between 0 and 1 are floored to 0, this behavior only happens in positive values as negative values work fine for margin

**Reproduced Bug**
[Codesandbox devbox ](https://codesandbox.io/p/devbox/styled-system-hy5rwh?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt0cy96b0007356hid4gtnwi%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt0cy96a0002356htk1wdfei%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt0cy96b0004356hvm4l2r3m%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt0cy96b0006356h1nqldbns%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt0cy96a0002356htk1wdfei%2522%253A%257B%2522id%2522%253A%2522clt0cy96a0002356htk1wdfei%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clt0cy96b0006356h1nqldbns%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt0cy96b0005356h1rhu4kl6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clt0cy96b0006356h1nqldbns%2522%252C%2522activeTabId%2522%253A%2522clt0cy96b0005356h1rhu4kl6%2522%257D%252C%2522clt0cy96b0004356hvm4l2r3m%2522%253A%257B%2522id%2522%253A%2522clt0cy96b0004356hvm4l2r3m%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt0cy96b0003356hyr5pls0j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clt0cy96b0003356hyr5pls0j%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by The-Code-Monkey** [comment]
@desouky95 you shouldn't really be doing floating point pixel placement as this is rounded by the browser anyway, in terms of your sandbox it doesn't work please fix this and I can double check the float values

**Comment by The-Code-Monkey** [comment]
So ive just added styled components to your sandbox and i can see what you mean, yes all values get parsed to absolutes as really you shouldn't be using non number values, if you want a custom value it should be added to the theme, however i can see why this has happened and i have updated space to include a check to see if its a string and if it is then return that value.
