### ISSUE TITLE
Setting bg prop effects color property

### ISSUE THREAD

**Issue by benjamingeorge** [The-Code-Monkey/styled-system#892]
When setting the prop `bg="transparent"` it also sets the color to #FFF effectively hiding all the content of that element.  This seems counterintuitive and causes unexpected results.  Removing "color" from this array fixes the problem.  I would create a PR but I'm unsure what the intent was here, especially with the use of `transform: contrastTransform` 
https://github.com/The-Code-Monkey/styled-system/blob/c3ea921e1e6a86f2ad3b3bab3740b725c9b1b00a/packages/styled-system/src/parsers/color.ts#L31

**Comment by The-Code-Monkey** [comment]
Yeah this was intentional but you have highlighted an issue in the transform. This could be fixed with a if statement due transparent. Feel free to make this PR

**Comment by benjamingeorge** [comment]
Not sure what Node version you are on but when I pull and yarn install I get 
``` 
.nvm/versions/node/v18.16.0/lib/node_modules/corepack/dist/lib/corepack.cjs:23250
const isURL = URL.canParse(range);                    
TypeError: URL.canParse is not a function
```

**Comment by The-Code-Monkey** [comment]
Hmm strange its running on latest node 18 and node 20 on the github actions, and using yarn 1.22, ill push a small change via the online editor in 10 mins or so.

**Comment by The-Code-Monkey** [comment]
@benjamingeorge I have pushed a change that should default to the base browser colour, if you have any further need to modify the colour you should be able to override this using the color prop itself.

**Comment by The-Code-Monkey** [comment]
new version is out please close the issue if this works.

**Comment by benjamingeorge** [comment]
Thanks
